arb-dir: lib/core/l10n/intl
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/gen
nullable-getter: false

# Prevent formatter from touching generated code
header: "// dart format off\n// coverage:ignore-file"
